import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";

import Footar from "@/components/Footar/Footar";






export const metadata: Metadata = {
  title: "SHOP MART",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
         <Navbar/>
       <div className=" container lg:max-w-7xl mx-auto p-3 my-30    ">
           <Toaster/>
          {children}
          
       </div>
       <Footar/>
      </body>
    </html>
  );
}
